_target_: w2ot.dual_trainer.DualTrainer

D:
  _target_: w2ot.models.icnn.ICNN
  dim_hidden: null # Automatically set

H:
  _target_: w2ot.models.init_nn.InitNN
  dim_hidden: null # Automatically set

input_dim: null # Automatically set
num_pretrain_iter: 10001
num_train_iter: 250001

pretrain_lr: 1e-3

lr_schedule_kwargs:
  init_value: 5e-4
  decay_steps: ${dual_trainer.num_train_iter}
  alpha: 1e-4

adamw_kwargs:
  b1: 0.5
  b2: 0.5
